### PR TITLE
Packages

### PR DESCRIPTION
**Pull request by ptomato**
Some changes that get me about half of the way there towards allowing all my plugins to work.

### CODE REVIEW

**Comment by rmacqueen** [comment]
Thanks! Finally got around to testing this. All looks good but when I go to "Install Package" using Package Control, nothing happens - I don't get a list of available packages showing up. Are you able to successfully install packages?

**Comment by ptomato** [comment]
I originally installed my packages by cloning https://github.com/ptomato/st2settings into the config directory and letting Package Control do the installing when starting up the app, and that worked fine. But I just tested installing a package with "Install Package" from the Ctrl+Shift+P menu and that works for me too. Any error messages in the journal perhaps?

**Comment by rmacqueen** [comment]
Works! Turns out Package Control won't work [unless your locale is set to `en_US`](https://github.com/wbond/package_control/issues/532), which is a curious limitation...

Sorry for the delay in getting this merged

**Comment by ptomato** [comment]
No worries. I'm going to try to improve this eventually by packaging up NPM modules such as jshint and jslint with Yarn and installing them during the build process, but I probably won't get around to that for a while.

**Pull request merged**
